repository: Atalantoo/atalantoo.github.io

# Server
url:         https://atalantoo.github.io/
encoding:    UTF-8

gems:
  - jekyll-sitemap

# Social
title: Atalantoo
description: Atalantoo is a game development studio located in Paris, France. The company develops top quality games for a broad range of digital platforms such as iOS, Android, Windows Phone, and Steam.
author: Damien Fremont
keywords: Atalantoo, Mobile Games, iPhone Games, iPad Games, Android Games, iOS, Android, Mac OS, Windows Phone, Games, Developer, Apps, Aplications, Software, Unity3D, Tools

twitter:     https://twitter.com/atalantoo
facebook:    https://www.facebook.com/atalantoo
youtube:     https://www.youtube.com/channel/UCHN8g_PTmmdkJ291QmNSjQA
instagram:   https://www.instagram.com/atalantoo
googleplus:  https://plus.google.com/b/109093386185193403190/109093386185193403190
windows:     .
android:     .
ios:         .
steam:       .

# Custom vars
browsercolor: #000
copyright: 2017 ATALANTOO. All Rights Reserved.

# Content
products:
  unity3d:
    title: 	Unity3D ALib
    desc: 	OpenSource extensions for Unity3D. This project provides UI (Material), localization (i18n), language traduction (l10n), charts (d3), REST Client (API), Auth (http, token), style (palettes).
  ci:
    title: 	Project CI
    desc: 	An omni-tool for Continuous Integration. It covers the full-stack, from specifications, to testing, deployment and supervision. Provide a a replacement for Jenkins, Ansible and Nagios.
  chronoquiz:
    title: 	Chrono Quiz
    desc: 	Coming soon.
  blast:
    title: 	Dino Blast!
    desc: 	A traditionnal ShootEmUp, set in a prehistoric universe.
