repository: Atalantoo/atalantoo.github.io

# Server
url:         https://atalantoo.github.io/
encoding:    UTF-8

gems:
  - jekyll-sitemap

# Social
title: Atalantoo
description: Atalantoo is a game development studio located in Paris, France. The company develops top quality games for a broad range of digital platforms such as iOS, Android, Windows Phone, and Steam.
author: Damien Fremont
keywords: Atalantoo, Mobile Games, iPhone Games, iPad Games, Android Games, iOS, Android, Mac OS, Windows Phone, Games, Developer, Apps, Aplications, Software, Unity3D, Tools

twitter:     https://twitter.com/atalantoo
facebook:    https://www.facebook.com/atalantoo
googleplus:  https://plus.google.com/b/109093386185193403190/109093386185193403190
linkedin:    https://linkedin.com/company/atalantoo

youtube:     https://www.youtube.com/channel/UCHN8g_PTmmdkJ291QmNSjQA
instagram:   https://www.instagram.com/atalantoo

windows:     .
android:     .
ios:         .
steam:       .

# Custom vars
browsercolor: #000
copyright: 2017 ATALANTOO. All Rights Reserved.
